In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 4, 5]])
arr

array([[1, 4, 5]])

In [3]:
arr.size

3

In [4]:
arr.shape

(1, 3)

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr[0,2]

5

In [7]:
arr[0,2]= 56

In [8]:
arr

array([[ 1,  4, 56]])

In [9]:
myarr = np.array([[4, 5, 7]], np.int64)
myarr

array([[4, 5, 7]], dtype=int64)

In [10]:
myarr.dtype

dtype('int64')

***Array creation: Conversion from other python structures***

In [11]:
listarr = np.array([[2,5,6],[2,5,6],[6,7,4]])
listarr

array([[2, 5, 6],
       [2, 5, 6],
       [6, 7, 4]])

In [12]:
listarr[1,1]

5

In [13]:
listarr.size

9

In [14]:
np.array({34,56})

array({56, 34}, dtype=object)

In [15]:
zeros = np.zeros((4,6))

In [16]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,5,5)
lspace

array([1., 2., 3., 4., 5.])

In [19]:
emp = np.empty((5,6))
emp

array([[7.09487313e-312, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000, 7.56571287e-307, 5.02034658e+175],
       [2.67788224e-032, 8.77477008e-071, 3.29586093e-032,
        8.01026121e+165, 4.22287705e-062, 6.14913903e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 2.67788224e-032, 8.77477008e-071,
        3.29586093e-032, 8.01026121e+165, 1.04915089e-153],
       [1.94918966e-153, 2.57707265e-057, 9.71521737e-067,
        3.37672040e-057, 2.59027896e-144, 7.79952704e-143]])

In [20]:
emp_like = np.empty_like(lspace)
emp_like

array([1., 2., 3., 4., 5.])

In [21]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
arrr = np.arange(99)
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arrr =arrr.reshape(3,33)

In [24]:
arrr.shape


(3, 33)

In [25]:
arrr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
arrr = arrr.ravel()

In [27]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
x = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
ar = np.array(x)

In [30]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
ar.sum(axis=0)

array([12, 15, 18])

In [32]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [33]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
ar.flat

In [35]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [36]:
ar.ndim

2

In [37]:
ar.nbytes

36

In [38]:
one = np.array([1, 4, 6, 7, 77, 78])
one.argmax()

5

In [39]:
one.argmin()

0

In [40]:
one.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [41]:
arr

array([[ 1,  4, 56]])

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.argmin()

0

In [44]:
ar.argmax()

8

In [45]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [46]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [47]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [48]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [50]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
ar3 = np.array([[1, 34, 3],[4, 5, 8],[7, 65, 9]])

In [52]:
ar3

array([[ 1, 34,  3],
       [ 4,  5,  8],
       [ 7, 65,  9]])

In [53]:
ar = ar.ravel()

In [54]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
ar = ar.reshape(3,3)

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar + ar3

array([[ 2, 36,  6],
       [ 8, 10, 14],
       [14, 73, 18]])

In [58]:
ar*ar3

array([[  1,  68,   9],
       [ 16,  25,  48],
       [ 49, 520,  81]])

In [59]:
ar.sum()

45

In [60]:
np.sqrt(ar3)

array([[1.        , 5.83095189, 1.73205081],
       [2.        , 2.23606798, 2.82842712],
       [2.64575131, 8.06225775, 3.        ]])

In [61]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [62]:
np.count_nonzero(ar)

9

In [63]:
import sys

In [64]:
ch_ar = [0, 5, 66, 43]

In [65]:
np_ar = np.array(ch_ar)

In [66]:
sys.getsizeof(1)* len(ch_ar)

112

In [67]:
np_ar.itemsize * np_ar.size

16

In [68]:
np_ar.tolist()

[0, 5, 66, 43]

In [69]:
ones_like = np.ones_like(ar3)

In [70]:
ones_like

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])